### ISSUE TITLE
install different version of Freeipa server

### ISSUE THREAD

**Issue by awsmaythem** [freeipa/ansible-freeipa#1036]
Hello
how can i install different version of Freeipa server deployment on my test server?
I need to install version 4.6.6 for deployment test cluster.

**Comment by rjeffman** [comment]
You would have to have the package available on the packages repositories, and than modify the proper `vars.yaml` file for your distribution under `ipaserver` role.

For example, this is the change I did to force the installation of `freeipa-server-4.10.0`, instead of the latest 4.10.1, in Fedora 37:

```diff
diff --git a/roles/ipaserver/vars/Fedora.yml b/roles/ipaserver/vars/Fedora.yml
index 1470134..cabb69d 100644
--- a/roles/ipaserver/vars/Fedora.yml
+++ b/roles/ipaserver/vars/Fedora.yml
@@ -1,7 +1,7 @@
 # defaults file for ipaserver
 # vars/Fedora.yml
 ---
-ipaserver_packages: [ "freeipa-server", "python3-libselinux" ]
-ipaserver_packages_dns: [ "freeipa-server-dns" ]
-ipaserver_packages_adtrust: [ "freeipa-server-trust-ad" ]
+ipaserver_packages: [ "freeipa-server-4.10.0", "python3-libselinux" ]
+ipaserver_packages_dns: [ "freeipa-server-dns-4.10.0" ]
+ipaserver_packages_adtrust: [ "freeipa-server-trust-ad-4.10.0" ]
 ipaserver_packages_firewalld: [ "firewalld" ]
```

Note that since most package managers handle dependency versions, you may need to specify the version of every package.

**Comment by rjeffman** [comment]
BTW... since it is not an "issue" (Bug/RFE) it would be a nice conversation to have under [Discussions](https://github.com/freeipa/ansible-freeipa/discussions). ;-)
