### ISSUE TITLE
please add ipa_timeout option to the new modules

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#128]
Hi,

Please add the ipa_timeout option to the new modules. 
(like ipahost and the others that don't have that option)

In slow environments (like my test lab) this is a very usefull option.

Rob

**Comment by t-woerner** [comment]
What behaviour do you expect in the timeout case? I think it is needed to verify if the IPA API is able to handle aborted commands without leading into corruption because of a partly execution.

**Comment by RobVerduijn** [comment]
also that
but I was thinking about the timeout that happens when using the ipa api the server might be slow to respond to your api request. (which could very well be caused by aborted/interupted commands)

**Comment by t-woerner** [comment]
I am not able to make sure that there will be no corruption because of running into the timeout. There are no tests for this scenario so far.
Also thinking about ipauser for example: I am not able to define a good timeout value as it might be used to add 5000 users or more in one task which will take some time. A timeout of 10 seconds will not be enough at all. Pushing the evaluation of the proper timeout value to the user is also not a good move in my opinion, especially as it depends heavily on the use case and environment.

**Comment by RobVerduijn** [comment]
I did not review the users module yet.

Nice to see you can create many at once even though the ipa api allows only the creation of one user at once.

I think the ansible asynchronous actions/polling is what you should be looking at when creating large numbers of users.
That way your module does not to figure out how long to wait for a 'add huge number of users' task to complete.

However the time to wait for a response from the api is still an issue, even with asynchrous.

**Comment by t-woerner** [comment]
The ipauser module is creating the list of commands to add all users internally. As this is done within one established connection it is a lot faster than calling the module for each single user separately.

**Comment by t-woerner** [comment]
Closing as we are not able to have a timeout that could not result in corruption.
