### ISSUE TITLE
RFE: ipagroup to allow user overides to be managed

### ISSUE THREAD

**Issue by chsnell** [freeipa/ansible-freeipa#421]
I would like to see ipagroup extended to handle the user overrides as well.  The group_add_member api does appear to have the ability to handle this with the idoverrideuser multivalue field.

Probably not a huge priority, but would be nice to have to fill out the module.

**Comment by rjeffman** [comment]
Hello, @chsnell .

I was playing around with idoverrideusers, and did an initial implementation to provide support for `idoverrideusers`, but I'm not able to test it, since I don't have an AD server to create a trust.

If you are willing to test it, it is available an my fork https://github.com/rjeffman/ansible-freeipa, branch `ipagroup_add_idoverrideuser`.

**Comment by chsnell** [comment]
Unfortunately, we have gone away from IPA in our environment due to it's inability to function to our needs, so I no longer have a test environment either.  I still think it's a nice feature to have to make it more complete to the API, and I appreciate the work the community did for us on these modules while we were trying to get things working.
