### ISSUE TITLE
firewall updates applied to default zone breaks DISA STIG

### ISSUE THREAD

**Issue by mralph-rh** [freeipa/ansible-freeipa#572]
The DISA STIG for RHEL 7 & 8 sets the default zone to DROP, which means that the ipa servers will not communicate properly.

The first ipa server in the environment will finish the install, but any replicas or clients will fail as they cannot communicate with the first ipa server because the ipa firewall services are installed in zone=drop instead of zone=public. Even if you manually fix the first ipa server, the replicas will still fail on install as their rules will still be installed in zone=drop.

ipa firewall rules need to be statically set to install in zone=public and not left to the default zone, or create an option to state which zone to use.

**Comment by rjeffman** [comment]
@mralph-rh, I'm not sure I understand the problem correctly, so correct me if I'm wrong. If I understood correctly, you cannot use the default firewall zone, but you can use another (non-default) zone.

If you have a permanent zone already set in your firewall, you can use `ipaserver_firewall_zone`, for the server, and `ipareplica_firewall_zone`, for replicas, to define which firewall zone `ipaserver` or `ipareplica` role will be configured by the role.

This variable is supported since release 0.2.0.

**Comment by mralph-rh** [comment]
@rjeffman just ignore me from now on. i apparently need new glasses as i did not see it. :(

**Comment by rjeffman** [comment]
@mralph-rh sometimes it is just too much work. :-)
