### ISSUE TITLE
Module is missing interpreter line

### ISSUE THREAD

**Issue by kpbll** [freeipa/ansible-freeipa#59]
ansible --version
ansible 2.7.6

Some modules does not work in current ansible version, I guess.
e.g. error:
module (ipaserver_master_password) is missing interpreter line

Root cause of that is including module file from another role:
ipaserver_master_password.py in ipareplica role contents:
../../ipaserver/library/ipaserver_master_password.py

One big repo is really not good and confuses me sometimes (related to https://github.com/freeipa/ansible-freeipa/issues/53)

**Comment by jlanclos** [comment]
I ran into this as well.. Appears to be caused by this commit https://github.com/freeipa/ansible-freeipa/commit/0a67c03116e7b78951619a73eba53f3c50ab2c9e 

The ipareplica role is using functions in ipaserver/module_utils/*

In my case, creating symlinks from ipaserver/module_utils/* to ipareplica/module_utils resolved this issue

**Comment by t-woerner** [comment]
Now I am able to understand the issue you are running into. I have not seen this so far. It is because of the reuse of ipaserver modules in ipareplica. I will create ipareplica modules that are not using ipaserver parts anymore to fix this.
