### ISSUE TITLE
Deployment using external CA

### ISSUE THREAD

**Issue by myllynen** [freeipa/ansible-freeipa#819]
When trying setup IdM with external CA using ansible-freeipa-1.6.3 on latest RHEL 8 I have defined these when running the IPA server role for the first time:

```
# External CA
ipaserver_external_ca: true
ipaserver_external_ca_type: generic
ipaserver_copy_csr_to_controller: true
```

The playbook completes ok and I get the CSR file in the controller as expected, so all looks good so far. But after signing the CSR and running playbook with an additional definition of:

```
ipaserver_external_cert_files_from_controller:
  - /root/chain.cert.pem
```

It starts ok but fails at task `Install - Setup CA` with `RuntimeError: CA configuration failed.` and _/var/log/ipaserver-install.log_ on IPA server saying:

```Installation failed: PKI subsystem 'CA' for instance 'pki-tomcat' already exists!```

I can't find hints from ansible-freeipa docs that would help to avoid this so this looks like a bug or an incomplete feature.

Please complete support for deployments with external CA and clarify the documentation as needed. Thanks.

**Comment by t-woerner** [comment]
You are setting `ipaserver_external_ca: yes` also for server installation step `. Use this setting only for step 1.

**Comment by myllynen** [comment]
Thanks a lot, it worked ok with your suggestion, closing!

**Comment by Keeper-of-the-Keys** [comment]
Hey sorry for re-opening this but I think that is more correct than opening a new ticket.

I just made the same mistake because I moved the vars to the host_vars file so rebuilding would be simple, this is I think also a common pattern expected by ansible users (to put the variable in host_vars/group_vars).

So I was thinking maybe the place that checks for `ipaserver_external_ca: yes` should also check for `ipaserver_external_cert_files` being a real file and if it is it can try to proceed with setup, like this you could even unify the 2 playbooks with a `ansible.builtin.pause` in between the two stages to allow the user to sign the csr after which s/he can allow the playbook to proceed to step 3.

It would look something like this (pseudo code cause I am still trying to understand the setup script):
```
if (ipaserver_external_ca && !valid_ca_crt(ipaserver_external_cert_files):
   generate_csr_type_setup()
else if (ipaserver_external_ca && valid_ca_crt(ipaserver_external_cert_files):
   setup_with_externally_signed_ca_crt()
else:
   normal_setup()
```
